export const experienceMetadata = {
  title: 'Sameh Hammad - My Experience | Frontend Developer | React.js, Next.js, Node.js, TypeScript',
  description: 'Explore the professional journey of Sameh Hammad, a Frontend Developer with expertise in React.js, Next.js, Node.js, TypeScript, and modern web technologies. Learn about his experience at ITI, Khamsat, Tech Sierra, and MHG Trading CJSC.',
  openGraph: {
    title: 'Sameh Hammad - My Experience | Frontend Developer | React.js, Next.js, Node.js, TypeScript',
    description: 'Discover the work experience of Sameh Hammad, a skilled Frontend Developer specializing in React.js, Next.js, Tailwind CSS, MongoDB, SQL, REST APIs, and DevOps. Worked at ITI, Khamsat, Tech Sierra, and MHG Trading CJSC.',
    type: 'website',
    url: 'https://sameh.online/about?my=experience',
    site_name: 'Sameh Hammad Portfolio',
    images: [
      {
        url: '/favicon.png', 
        width: 800,
        height: 600,
        alt: 'Sameh Hammad - My Experience',
      },
    ],
  },
  keywords: [
    'Sameh Hammad Experience',
    'Frontend Developer Experience',
    'React.js Developer',
    'Next.js Developer',
    'Node.js Developer',
    'TypeScript Developer',
    'MongoDB Developer',
    'SQL Developer',
    'REST API Integration',
    'DevOps for Frontend',
    'Freelance Web Developer',
    'Khamsat Freelancer',
    'Tech Sierra Part-time',
    'MHG Trading CJSC',
    'Information Technology Institute (ITI)',
    'Web Development Cairo',
    'Frontend Intern ITI',
    'Remote Frontend Work',
    'Responsive Web Applications',
    'UI/UX Design Experience',
  ],
};
