export const metadata = {
    title: 'Sameh Hammad | Front-End Developer | React.js, Next.js, Angular',
    description: 'Sameh Hammad - Front-End Developer specializing in React.js, Next.js. Based in Cairo, Egypt. Contact: +201112967597. Available for web development, UI/UX design, REST APIs,SQL|| NoSQL databases, and (ecommerce || branding || portfolio || blogs || courses websites || CMS ) projects.',
    keywords: [
      'Front-End Developer',
      'React.js Developer',
      'Next.js Developer',
      'Angular Developer',
      'JavaScript Developer',
      'Web Developer Cairo Egypt',
      'Freelance Web Developer',
      'UI/UX Designer',
      'SQL Developer',
      'Next.js Expert',
      'Next js',
      'React js',
      'Angular',
      'Tailwind CSS',
      'MHG',
      'NoSQL Developer',
      'MongoDB Expert',
      'REST API Development',
      'Git Version Control',
      'Remote Front-End Developer',
      'Bootstrap and Tailwind CSS',
      'SEO-Friendly Websites',
      'Performance Optimization',
      'Responsive Design',
       'Ecommerce Websites',
      'Portfolio Websites',
      'Blog Websites',
      'Branding Websites',
      'Course Websites',
       'Content Writing',
       'CMS Websites',
       'Web Analytics',
      'Cross-Browser Compatibility',
      'Cross-Platform Compatibility',
      'Cross-Device Compatibility',
      'Cross-Organization Compatibility',
      'Cross-Functional Compatibility',
    ],
    openGraph: {
      title: 'Sameh Hammad | Front-End Developer | React.js, Next.js, Angular',
      description: 'Experienced Front-End Developer specializing in modern JavaScript frameworks like React.js, Next.js, and Angular. Available for freelance and remote work worldwide. Contact: +201112967597.',
      type: 'website',
      url: 'https://sameh.online', 
      site_name: 'Sameh Hammad Portfolio',
      locale: 'en_US',
      images: [
        {
          url: '/favicon.png',
          width: 1200,
          height: 630,
          alt: 'Sameh Hammad - Front-End Developer',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Sameh Hammad | Front-End Developer | React.js, Next.js, Angular Expert',
      description: 'Front-End Developer based in Cairo, Egypt. Specialized in React.js, Next.js, and Angular. Available for freelance and remote work.',
      site: '@samehhammad',
      image:'/favicon.png',
    },
    icons: {
      icon: '/favicon.png',
    },
    contact: {
      email: 'sam7hammad@gmail.com',
      phone: '+201112967597',
      location: 'Cairo, Egypt',
      website: 'https://sameh.online',
    },
  };
  