export const metadata = {
    title: 'Sameh Hammad - My Skills | Frontend Developer | React js, Next.js, Node.js, TypeScript',
    description: 'Learn more about Sameh Hammad, a Frontend Developer with 2+ years of experience in building responsive websites and applications using React, Next.js, Node.js, TypeScript, AWS, and more. Based in Cairo, Egypt.',
    openGraph: {
      title: 'Sameh Hammad - My Skills | Frontend Developer | React js, Next.js, Node.js, TypeScript Expert',
      description: 'Learn more about Sameh Hammad, a Frontend Developer with 2+ years of experience in building responsive websites and applications using React, Next.js, Node.js, TypeScript, AWS, and more. Based in Cairo, Egypt.',
      type: 'website',
      url: 'https://sameh.online/about?my=skills',
      site_name: 'Sameh Hammad Portfolio',
      images: [
        {
          url: '/favicon.png', 
          width: 800,
          height: 600,
          alt: 'Sameh Hammad - My Skills',
        },
      ],
    },
    keywords: [
      'Sameh Hammad About',
      'Frontend Developer Cairo',
      'React Developer',
      'Next.js Developer',
      'Node.js Developer',
      'TypeScript Developer',
      'JavaScript Developer',
      'AWS Developer',
      'Git Developer',
      'GitHub Developer',
      'Docker Developer',
      'MongoDB Developer',
      'MySQL Developer',
      'Sanity Developer',
      'Firebase Developer',
      'Responsive Web Design',
      'Freelance Developer Cairo',
      'ITI Graduate',
      'Senior Developer',
      'Junior Developer',
      'Web Development Cairo',
      'UI/UX Design',
    ],
  };